# cloud/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iot-dashboard
  template:
    metadata:
      labels:
        app: iot-dashboard
    spec:
      containers:
      - name: dashboard
        image: your-docker-image:latest
        ports:
        - containerPort: 5000
