# configs/model_config.yaml

model:
  name: "RandomForestClassifier"
  parameters:
    n_estimators: 100             # Number of trees in the forest
    max_depth: 10                 # Maximum depth of the trees
    min_samples_split: 2          # Minimum number of samples required to split a node
    min_samples_leaf: 1           # Minimum number of samples required to be at a leaf node
    random_state: 42              # Random seed for reproducibility

training:
  test_size: 0.2                  # Test set size as a fraction of total data
  random_state: 42                # Seed for train-test split

evaluation:
  metrics:                        # Metrics to evaluate the model
    - accuracy
    - precision
    - recall

